<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsRO0l7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsRO0l7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOsRO0l7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOsRO0l7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOsRO0l7\App_KernelDevDebugContainer([
    'container.build_hash' => 'OsRO0l7',
    'container.build_id' => 'ff2d2a09',
    'container.build_time' => 1596220636,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsRO0l7');
